{% set version = "6.0.7" %}
{% set fabm_version = "2.1.0" %}
{% set build = 0 %}

package:
  name: gotm
  version: {{ version }}

source:
  - url: https://github.com/gotm-model/code/releases/download/v{{ version }}/code.tar.gz
    sha256: e0e22e1d461215f4ce0ca827c6545ba4a89d1869727442e06602f0d9b76cda55
    folder: gotm
  - url: https://github.com/fabm-model/fabm/releases/download/v{{ fabm_version }}/code.tar.gz
    sha256: a2b551669acfcff4018e9d8b19d83100c26aac12dba3699d0976448ccdfc0717
    folder: fabm
    patches:
      - ersem.patch
      - ogs.patch

build:
  number: {{ build }}

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}        # [unix]
    - make                             # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib("c") }}    # [win]
  host:
    - netcdf-fortran
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  commands:
    - gotm --version

about:
  home: https://gotm.net
  summary: 'General Ocean Turbulence Model'
  description: |
    The General Ocean Turbulence Model (GOTM) is a one-dimensional water column
    model. It includes a set of state-of-the-art turbulence closure models and,
    through FABM <https://fabm.net>, a comprehensive library of biogeochemical
    models.
  license: GPL-2.0-only
  license_family: GPL
  license_file: gotm/COPYING
  dev_url: https://github.com/gotm-model/code

extra:
  recipe-maintainers:
    - jornbr
    - bolding
