{% set version = "6.0.8" %}
{% set fabm_version = "2.1.2" %}
{% set build = 0 %}

package:
  name: gotm
  version: {{ version }}

source:
  - url: https://github.com/gotm-model/code/releases/download/v{{ version }}/code.tar.gz
    sha256: 80e2496e227939a8b4634ef348eae3ae5ea83d1502a8804c034f3ce934fd94fb
    folder: gotm
  - url: https://github.com/fabm-model/fabm/releases/download/v{{ fabm_version }}/code.tar.gz
    sha256: 16ca4cfe6247a2a45e040a68939995002dcc007a37dcb44d0f2484075d95e868
    folder: fabm
    #patches:
    #  - ersem.patch
    #  - ogs.patch

build:
  number: {{ build }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}        # [unix]
    - {{ stdlib("c") }}                # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
  host:
    - netcdf-fortran
  run:
    #- m2w64-gcc-libgfortran            # [win]

test:
  commands:
    - gotm --version

about:
  home: https://gotm.net
  summary: 'General Ocean Turbulence Model'
  description: |
    The General Ocean Turbulence Model (GOTM) is a one-dimensional water column
    model. It includes a set of state-of-the-art turbulence closure models and,
    through FABM <https://fabm.net>, a comprehensive library of biogeochemical
    models.
  license: GPL-2.0-only
  license_family: GPL
  license_file: gotm/COPYING
  dev_url: https://github.com/gotm-model/code

extra:
  recipe-maintainers:
    - jornbr
    - bolding
