{% set version = "6.0.5" %}
{% set fabm_version = "2.0.0" %}
{% set build = 1 %}

package:
  name: gotm
  version: {{ version }}

source:
  - url: https://github.com/gotm-model/code/releases/download/v{{ version }}/code.tar.gz
    sha256: 7315a421f7684471423dce25424945614f32b73ac1e630a813ccead77a9afffe
    folder: gotm
  - url: https://github.com/fabm-model/fabm/releases/download/v{{ fabm_version }}/code.tar.gz
    sha256: 30bbe419d3ef84042f626c7830c8e82d7fee346ca1e374cb30b48716adabffc6
    folder: fabm
    patches:
    - ersem.patch

build:
  number: {{ build }}

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}  # [unix]
    - make  # [unix]

    # netcdf-fortran gets its Fortran compiler on Windows with
    # compiler('m2w64_fortran') but that does not seem to work for us
    # Error: Unsatisfiable dependencies ... ['m2w64_fortran_win-64']
    #- {{ compiler('m2w64_fortran') }}  # [win]
    - m2w64-gcc-fortran  # [win]

    # netcdf-fortran uses m2-make, but that does not result in a make
    # program that CMake's MinGW generator recognizes
    #- m2-make  # [win]
    - m2w64-make  # [win]
  host:
    - netcdf-fortran
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  commands:
    - gotm --version

about:
  home: https://gotm.net
  summary: 'General Ocean Turbulence Model'
  description: |
    The General Ocean Turbulence Model (GOTM) is a one-dimensional water column
    model. It includes a set of state-of-the-art turbulence closure models and,
    through FABM <https://fabm.net>, a comprehensive library of biogeochemical
    models.
  license: GPL-2.0-only
  license_family: GPL
  license_file: gotm/COPYING
  dev_url: https://github.com/gotm-model/code

extra:
  recipe-maintainers:
    - jornbr
    - bolding
